### ISSUE TITLE
Wireframe About section

### ISSUE THREAD

**Issue by bradnunnally** [USDepartmentofLabor/worker-dol-gov#12]
Wireframe the about section to cover things like the Mission, Claims Process, and Supporting Agencies.

**Comment by nicoleslaw** [comment]
Some ideas:
+ brief intro about this site/effort
+ basic contact info for each agency

**Comment by nicoleslaw** [comment]
@ericronne @bradnunnally Can we close this?

**Comment by bradnunnally** [comment]
Yup!
