### ISSUE TITLE
Explore different typography

### ISSUE THREAD

**Issue by ericronne** [USDepartmentofLabor/worker-dol-gov#3]
The site currently uses Montserrat (headings) and Helvetica Neue (body). Both convey an appropriate tone, but let's see if we can find options that pair a little better. Or even trim it back to only one font.

**Comment by ericronne** [comment]
@noahmanger what do you think of ` Helvetica, Arial, sans-serif ` for the stack?
So mac users, at least, get treated to helvetica ;)

cc @nicoleslaw

**Comment by noahmanger** [comment]
I support it. I don't think we need to go to lowest-common-denominator if there's a fall-back.

**Comment by ericronne** [comment]
cool let's.
