### ISSUE TITLE
Footer structure

### ISSUE THREAD

**Issue by ericronne** [USDepartmentofLabor/worker-dol-gov#32]
@nicoleslaw just my gut talking, but i wonder if a small heading over the right column of the footer would make things more clear. Currently "Contact us" sort of functions as the "title" for the entire footer, which is why i wonder...

![image](https://user-images.githubusercontent.com/9259185/29032487-2844899e-7b57-11e7-950a-bc2fcb2fe8e1.png)

**Comment by nicoleslaw** [comment]
Hmm, I will think about it. I want to wait to see if they have other link additions once OPA reviews.

**Comment by noahmanger** [comment]
We also need actual links for those links. They don't go anywhere now.

**Comment by ericronne** [comment]
I think i have those links. Hold, pls..

**Comment by nicoleslaw** [comment]
I added the links 👍

**Comment by ericronne** [comment]
Oh! Cool. I had a different foia link, which i added...
https://www.dol.gov/general/foia

**Comment by noahmanger** [comment]
Done.
