### ISSUE TITLE
Move "W" out of the shield in the logo -> and improve it in general

### ISSUE THREAD

**Issue by ericronne** [USDepartmentofLabor/worker-dol-gov#4]
For readability's sake, the "W" should be closer to "ORKER." For the sake of time, let's simply move the shield to the left of everything, and possibly adjust the color. Time permitting, perhaps we can do further concepting on the icon itself.

![image](https://user-images.githubusercontent.com/9259185/28581326-ec89619e-712f-11e7-8e9e-90876faee09d.png)

**Comment by ericronne** [comment]
Done, but keeping issue open since i want to improve it! …
![image](https://user-images.githubusercontent.com/9259185/28837066-0f726490-76b1-11e7-929f-a0cc0447d0cb.png)

**Comment by ericronne** [comment]
here's a mod
 - different shield shape fixes "mortal and pestle" visual connection
 - simpler shield ... simple is usually better!
 - literal person in shield obviously says "people protection" (erring on the side of literal feels ok to me in this context)

![image](https://user-images.githubusercontent.com/9259185/28890356-682de6f0-778c-11e7-8dc5-872112f7db75.png)

pls lmk your thoughts @noahmanger @nicoleslaw

**Comment by noahmanger** [comment]
I love it. Adding the person there really helps.

**Comment by nicoleslaw** [comment]
I don't have an opinion here, other than that it reminds me of a police badge... Sorry I'm not being helpful!

**Comment by ericronne** [comment]
That's a 💯 % valid opinion! **I think testing should be a road map item.**

Fwiw, i just noticed this icon this morning in chrome, for "my account." To me, it suggests security, which is very much in line with cops, of course. I'll keep thinking; might be able to tweak a little before the clock runs out...

![image](https://user-images.githubusercontent.com/9259185/28922709-ded59b88-7820-11e7-94ec-1d8bb04ce350.png)

**Comment by ericronne** [comment]
Removing blue could help reduce that connection.
![image](https://user-images.githubusercontent.com/9259185/28925717-4afbca12-782b-11e7-985d-345e92658409.png)


![image](https://user-images.githubusercontent.com/9259185/28925842-a667784c-782b-11e7-9c99-1be5dbe1e789.png)
